services:
  meedeeapi:
    image: tkp7663/tharakorn:5.25.9
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    volumes:
      - "my_data:/app/uploads" # Mount โค้ดจากเครื่อง host ไปยัง container
    ports:
      - "3210:3000"
volumes:
  my_data:
    name: upload_custom_volume  # ตั้งชื่อ volume แบบกำหนดเอง